### ISSUE TITLE
Delete/get the same key leads to seg fault

### ISSUE THREAD

**Issue by tappara** [nomemory/open-adressing-hash-table-c#1]
Hi Andrei, 
I like your implementation: very neat, thanks for sharing it.

`oa_hash_put(p_oa_hash, (const void*) &key, (const void *) &val);`
`p_val = oa_hash_get(p_oa_hash, (const void*) &key);`
`oa_hash_delete(p_oa_hash, (const void*) &key);`
`p_val= oa_hash_get(p_oa_hash, (const void*) &key);`

Any idea what's going on there?
Thanks in advance for your answer!

**Comment by tappara** [comment]
Andrei, 
the issue is in my implementation of the 'eq' operation on int32 keys:

// Check if two int32 are equal
bool ch_int32_eq(const void *data1, const void *data2, void *arg) {
  (void)arg;
  int32_t int1 = *((int32_t*) data1);
  int32_t int2 = *((int32_t*) data2);
  return (int1==int2)?true:false;    
}

which deference a null pointer, my bad. In the "strings" implementation for this operator, the function `strcmp` 'masks' the issue.

The fix is trivial, of course:

// Check if two int32 are equal
bool ch_int32_eq(const void *data1, const void *data2, void *arg) {
  (void)arg;
  if (NULL == data1 || NULL == data2) {
    return false;
  }
  int32_t int1 = *((int32_t*) data1);
  int32_t int2 = *((int32_t*) data2);
  return (int1==int2)?true:false;    
}

Sorry for the "noise".

**Comment by nomemory** [comment]
Hello @tappara , no issues. Thank you for analysing the code, and contributing. No noise. Glad everything went well. 

If you are interested to know more about open addressing hashing I also recommend reading: 

https://www.andreinc.net/2021/11/08/a-tale-of-java-hash-tables
